# Generated by Django 5.2 on 2025-04-14 17:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_student_telegram_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject_study",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="gpa",
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bd_one",
                    models.IntegerField(
                        default=0,
                        max_length=100,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "bd_two",
                    models.IntegerField(
                        default=0,
                        max_length=100,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "exam",
                    models.IntegerField(
                        default=0,
                        max_length=100,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "final_grade",
                    models.FloatField(
                        default=0.0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.student"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.subject_study",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="subject_study",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.teacher"
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.teacher"
            ),
        ),
    ]
