# Generated by Django 5.2 on 2025-04-14 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_subject_study_teacher_student_gpa_grade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="bd_one",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="bd_two",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="exam",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
    ]
