# Generated by Django 5.2 on 2025-04-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_grade_bd_one_alter_grade_bd_two_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="face_image",
            field=models.ImageField(blank=True, null=True, upload_to="students/"),
        ),
    ]
