# Generated by Django 5.2 on 2025-04-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_marks"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Marks",
            new_name="Mark",
        ),
    ]
