# Generated by Django 5.2 on 2025-05-06 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_remove_teacher_subject_alter_schedule_subject"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Mark",
            new_name="Attendance",
        ),
    ]
