# Generated by Django 5.2 on 2025-05-06 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_attendance_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="app.subject_study",
            ),
        ),
    ]
