# Generated by Django 5.2 on 2025-05-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_alter_attendance_schedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="time",
        ),
        migrations.AddField(
            model_name="attendance",
            name="marked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
