# Generated by Django 5.2.7 on 2026-01-03 13:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_remove_attendance_subject_remove_attendance_time_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={
                "verbose_name": "Посещаемость",
                "verbose_name_plural": "Посещаемости",
            },
        ),
        migrations.AlterModelOptions(
            name="grade",
            options={"verbose_name": "Оценка", "verbose_name_plural": "Оценки"},
        ),
        migrations.AlterModelOptions(
            name="group",
            options={"verbose_name": "Группа", "verbose_name_plural": "Группы"},
        ),
        migrations.AlterModelOptions(
            name="schedule",
            options={"verbose_name": "Расписание", "verbose_name_plural": "Расписания"},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "Студент", "verbose_name_plural": "Студенты"},
        ),
        migrations.AlterModelOptions(
            name="subject_study",
            options={"verbose_name": "Предмет", "verbose_name_plural": "Предметы"},
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={
                "verbose_name": "Преподаватель",
                "verbose_name_plural": "Преподаватели",
            },
        ),
        migrations.AlterField(
            model_name="attendance",
            name="marked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Отмечено в"
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="presense",
            field=models.BooleanField(default=False, verbose_name="Присутствие"),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="app.schedule",
                verbose_name="Занятие",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance",
                to="app.student",
                verbose_name="Студент",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="bd_one",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="BD 1",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="bd_two",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="BD 2",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="exam",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="Экзамен",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="final_grade",
            field=models.FloatField(
                default=0.0,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="Итоговая оценка",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.student",
                verbose_name="Студент",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.subject_study",
                verbose_name="Предмет",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="course",
            field=models.CharField(max_length=50, verbose_name="Курс"),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название группы"),
        ),
        migrations.AlterField(
            model_name="group",
            name="students",
            field=models.ManyToManyField(
                related_name="groups", to="app.student", verbose_name="Студенты"
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="date",
            field=models.DateField(verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.group",
                verbose_name="Группа",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.subject_study",
                verbose_name="Предмет",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.teacher",
                verbose_name="Преподаватель",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="time",
            field=models.TimeField(verbose_name="Время"),
        ),
        migrations.AlterField(
            model_name="student",
            name="address",
            field=models.TextField(verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="student",
            name="age",
            field=models.IntegerField(verbose_name="Возраст"),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="student",
            name="face_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="students/", verbose_name="Фото"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="student",
            name="gpa",
            field=models.FloatField(default=0.0, verbose_name="GPA"),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(max_length=15, verbose_name="Телефон"),
        ),
        migrations.AlterField(
            model_name="student",
            name="telegram_id",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="Telegram ID"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="telegram_username",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Telegram username"
            ),
        ),
        migrations.AlterField(
            model_name="subject_study",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="subject_study",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название предмета"),
        ),
        migrations.AlterField(
            model_name="subject_study",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.teacher",
                verbose_name="Преподаватель",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="phone",
            field=models.CharField(max_length=15, verbose_name="Телефон"),
        ),
    ]
