# Generated by Django 5.2 on 2026-01-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0015_alter_attendance_options_alter_grade_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="address",
        ),
        migrations.RemoveField(
            model_name="student",
            name="gpa",
        ),
        migrations.AddField(
            model_name="student",
            name="platonus_id",
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name="ID platonus"),
        ),
    ]
