# Generated by Django 5.2.7 on 2026-01-07 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("app", "0016_remove_student_address_remove_student_gpa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.teacherprofile",
                verbose_name="Преподаватель",
            ),
        ),
        migrations.AlterField(
            model_name="subject_study",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.teacherprofile",
                verbose_name="Преподаватель",
            ),
        ),
        migrations.DeleteModel(
            name="Teacher",
        ),
    ]
