# Generated by Django 5.2.7 on 2026-01-07 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("app", "0017_alter_schedule_teacher_alter_subject_study_teacher_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="teacher",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.teacherprofile",
                verbose_name="Преподаватель",
            ),
            preserve_default=False,
        ),
    ]
