# Generated by Django 5.2.7 on 2026-01-07 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("app", "0018_group_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.teacherprofile",
                verbose_name="Преподаватель",
            ),
        ),
    ]
