# Generated by Django 5.2.7 on 2026-01-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_alter_group_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="groups",
                to="app.student",
                verbose_name="Студенты",
            ),
        ),
    ]
