# Generated by Django 5.2.7 on 2026-01-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_alter_group_students"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                related_name="groups",
                to="app.student",
                verbose_name="Студенты",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Platonus Email"),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Телефон"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="telegram_id",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Telegram ID",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="telegram_username",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Telegram username",
            ),
        ),
    ]
