# Generated by Django 5.2.7 on 2026-01-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0021_alter_group_students_alter_student_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="specialty_group",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Специальность"
            ),
        ),
    ]
