# Generated by Django 5.2.7 on 2026-01-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0022_group_specialty_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="specialty_group",
        ),
        migrations.AddField(
            model_name="group",
            name="group_specialty",
            field=models.CharField(default=1, max_length=100, verbose_name="Специальность"),
            preserve_default=False,
        ),
    ]
