# Generated by Django 5.2.7 on 2026-01-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("app", "0023_remove_group_specialty_group_group_group_specialty"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                fields=("name", "teacher"), name="unique_group_name_per_teacher"
            ),
        ),
    ]
