# Generated by Django 5.2.7 on 2026-01-11 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0024_group_unique_group_name_per_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total",
                    models.PositiveBigIntegerField(default=0, verbose_name="Всего занятий"),
                ),
                (
                    "attended",
                    models.PositiveBigIntegerField(default=0, verbose_name="Посещено занятий"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено в"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.group",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.student",
                        verbose_name="Студент",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.subject_study",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статистика посещаемости",
                "verbose_name_plural": "Статистика посещаемости",
                "indexes": [
                    models.Index(
                        fields=["subject", "group"],
                        name="app_attenda_subject_5a9f32_idx",
                    ),
                    models.Index(
                        fields=["student", "subject"],
                        name="app_attenda_student_184c12_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "subject", "group"),
                        name="uniq_stat_student_subject_group",
                    )
                ],
            },
        ),
    ]
