# Generated by Django 5.2.7 on 2026-01-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_attendancestat"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject_study",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="subjects",
                to="app.group",
                verbose_name="Группы",
            ),
        ),
    ]
