# Generated by Django 5.2.7 on 2026-01-18 19:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0026_subject_study_groups"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Grade",
        ),
    ]
