# Generated by Django 5.2.7 on 2026-01-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("app", "0027_delete_grade"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["schedule"], name="app_attenda_schedul_5cc1a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["student"], name="app_attenda_student_fe6358_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(
                fields=["group", "date"], name="app_schedul_group_i_abadd3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(
                fields=["teacher", "date"], name="app_schedul_teacher_de9427_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("student", "schedule"), name="uniq_attendance_student_schedule"
            ),
        ),
        migrations.AddConstraint(
            model_name="schedule",
            constraint=models.UniqueConstraint(
                fields=("group", "date", "time"), name="uniq_schedule_group_date_time"
            ),
        ),
    ]
