# Generated by Django 5.2.7 on 2026-02-01 17:43

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0028_attendance_app_attenda_schedul_5cc1a1_idx_and_more"),
    ]

    operations = [
        VectorExtension(),
    ]
