# Generated by Django 5.2.7 on 2026-02-01 17:43

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0029_vector_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="face_embadding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=512,
                null=True,
                verbose_name="Биометрические данные лица",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="face_updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата обновления биометрии лица"
            ),
        ),
    ]
