# Generated by Django 5.2.7 on 2026-02-01 22:50

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0030_student_face_embadding_student_face_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentFaceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="students/faces/", verbose_name="Фото лица")),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=512,
                        null=True,
                        verbose_name="Эмбеддинг лица",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_images",
                        to="app.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото лица студента",
                "verbose_name_plural": "Фото лиц студентов",
            },
        ),
    ]
