# Generated by Django 5.2.7 on 2026-02-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0031_student_face_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
            },
        ),
    ]
