# Generated by Django 5.2.7 on 2026-02-27 23:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("app", "0032_notificationmodels"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("IN_APP", "В приложении"),
                            ("EMAIL", "Email"),
                            ("TELEGRAM", "Telegram"),
                        ],
                        max_length=20,
                        verbose_name="Канал доставки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Ожидается"),
                            ("SENT", "Отправлено"),
                            ("FAILED", "Ошибка отправки"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Статус доставки",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Цель доставки",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество попыток доставки"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True, null=True, verbose_name="Последняя ошибка доставки"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата отправки"),
                ),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ID сообщения от провайдера",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Доставка уведомления",
                "verbose_name_plural": "Доставки уведомлений",
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(default=False, verbose_name="Включены уведомления"),
                ),
                (
                    "allow_email",
                    models.BooleanField(default=False, verbose_name="Разрешить email уведомления"),
                ),
                (
                    "allow_telegram",
                    models.BooleanField(
                        default=False, verbose_name="Разрешить Telegram уведомления"
                    ),
                ),
                (
                    "threshold_percent",
                    models.PositiveSmallIntegerField(
                        default=60,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Порог для уведомлений об успеваемости (%)",
                    ),
                ),
                (
                    "drop_delta_percent",
                    models.PositiveSmallIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Порог для уведомлений об ухудшении успеваемости (%)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Настройка уведомлений",
                "verbose_name_plural": "Настройки уведомлений",
            },
        ),
        migrations.AddField(
            model_name="notificationmodels",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("SCHEDULE", "Расписание"),
                    ("GROUP", "Группа"),
                    ("STUDENT", "Студент"),
                    ("PERFORMANCE", "Успеваемость"),
                ],
                default=1,
                max_length=20,
                verbose_name="Тип события",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notificationmodels",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="notifications/",
                verbose_name="Изображение",
            ),
        ),
        migrations.AddField(
            model_name="notificationmodels",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="Прочитано"),
        ),
        migrations.AddField(
            model_name="notificationmodels",
            name="message_format",
            field=models.CharField(
                choices=[("TEXT", "Текст"), ("MARKDOWN", "Markdown"), ("HTML", "HTML")],
                default="TEXT",
                max_length=20,
                verbose_name="Формат сообщения",
            ),
        ),
        migrations.AddField(
            model_name="notificationmodels",
            name="payload",
            field=models.JSONField(blank=True, null=True, verbose_name="Данные события"),
        ),
        migrations.AddField(
            model_name="notificationmodels",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата прочтения"),
        ),
        migrations.AddField(
            model_name="notificationmodels",
            name="recipient_student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="app.student",
                verbose_name="Получатель студент",
            ),
        ),
        migrations.AddField(
            model_name="notificationmodels",
            name="recipient_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="accounts.teacherprofile",
                verbose_name="Получатель преподаватель",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationmodels",
            index=models.Index(
                fields=["recipient_teacher", "-created_at"],
                name="notif_teacher_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationmodels",
            index=models.Index(
                fields=["recipient_student", "-created_at"],
                name="notif_student_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationmodels",
            index=models.Index(fields=["is_read", "-created_at"], name="notif_isread_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="notificationmodels",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("recipient_teacher__isnull", False),
                        ("recipient_student__isnull", True),
                    ),
                    models.Q(
                        ("recipient_teacher__isnull", True),
                        ("recipient_student__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="notification_exactly_one_recipient",
            ),
        ),
        migrations.AddField(
            model_name="notificationdelivery",
            name="notification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="app.notificationmodels",
                verbose_name="Уведомление",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preference",
                to="app.student",
                verbose_name="Студент",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(fields=["status", "channel"], name="notifdel_status_channel_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(fields=["notification", "status"], name="notifdel_notif_status_idx"),
        ),
    ]
