# Generated by Django 5.2.7 on 2026-02-27 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("app", "0033_notificationdelivery_notificationpreference_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notificationmodels",
            name="notification_exactly_one_recipient",
        ),
        migrations.RemoveIndex(
            model_name="notificationdelivery",
            name="notifdel_status_channel_idx",
        ),
        migrations.RemoveIndex(
            model_name="notificationdelivery",
            name="notifdel_notif_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="notificationmodels",
            name="notif_teacher_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="notificationmodels",
            name="notif_student_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="notificationmodels",
            name="notif_isread_created_idx",
        ),
        migrations.RenameField(
            model_name="notificationmodels",
            old_name="read_at",
            new_name="readt_at",
        ),
        migrations.RemoveField(
            model_name="notificationdelivery",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="notificationdelivery",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="notificationdelivery",
            name="attempts",
            field=models.IntegerField(default=0, verbose_name="Количество попыток доставки"),
        ),
        migrations.AlterField(
            model_name="notificationdelivery",
            name="notification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="app.notificationmodels",
            ),
        ),
        migrations.AlterField(
            model_name="notificationmodels",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="notificationmodels",
            name="message_format",
            field=models.CharField(default="TEXT", max_length=20, verbose_name="Формат сообщения"),
        ),
        migrations.AlterField(
            model_name="notificationmodels",
            name="recipient_student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="app.student",
            ),
        ),
        migrations.AlterField(
            model_name="notificationmodels",
            name="recipient_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="accounts.teacherprofile",
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="allow_email",
            field=models.BooleanField(default=True, verbose_name="Разрешить email уведомления"),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="allow_telegram",
            field=models.BooleanField(default=True, verbose_name="Разрешить Telegram уведомления"),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="drop_delta_percent",
            field=models.IntegerField(
                default=10,
                verbose_name="Порог для уведомлений об ухудшении успеваемости (%)",
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="enabled",
            field=models.BooleanField(default=True, verbose_name="Включены уведомления"),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preference",
                to="app.student",
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="threshold_percent",
            field=models.IntegerField(
                default=60, verbose_name="Порог для уведомлений об успеваемости (%)"
            ),
        ),
    ]
