# Generated by Django 5.2.7 on 2026-04-10 13:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        (
            "app",
            "0034_remove_notificationmodels_notification_exactly_one_recipient_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationmodels",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("SCHEDULE", "Расписание"),
                    ("GROUP", "Группа"),
                    ("STUDENT", "Студент"),
                    ("PERFORMANCE", "Успеваемость"),
                    ("RISK", "Риск студента"),
                ],
                max_length=20,
                verbose_name="Тип события",
            ),
        ),
        migrations.CreateModel(
            name="RiskIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("ATTENDANCE", "Посещаемость"),
                            ("ACADEMIC", "Успеваемость"),
                            ("PAYMENT", "Оплата"),
                            ("GENERAL", "Общий риск"),
                        ],
                        max_length=20,
                        verbose_name="Тип инцидента",
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(max_length=64, verbose_name="Код причины"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Открыт"),
                            ("ACKNOWLEDGED", "Подтвержден"),
                            ("ESCALATED", "Эскалирован"),
                            ("RESOLVED", "Решен"),
                        ],
                        default="OPEN",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("problem", models.CharField(max_length=255, verbose_name="Проблема")),
                ("reason", models.TextField(verbose_name="Причина")),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Контакт для обращения"
                    ),
                ),
                (
                    "metric_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Название метрики"),
                ),
                (
                    "metric_value",
                    models.FloatField(blank=True, null=True, verbose_name="Текущее значение"),
                ),
                (
                    "threshold_value",
                    models.FloatField(blank=True, null=True, verbose_name="Пороговое значение"),
                ),
                (
                    "metric_unit",
                    models.CharField(blank=True, max_length=20, verbose_name="Единица измерения"),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, null=True, verbose_name="Данные инцидента"),
                ),
                (
                    "first_detected_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Первое выявление"),
                ),
                (
                    "last_detected_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Последнее выявление",
                    ),
                ),
                (
                    "due_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Срок исправления"),
                ),
                (
                    "notification_sent_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Первое уведомление отправлено",
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Подтверждено преподавателем",
                    ),
                ),
                (
                    "escalated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата эскалации"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата решения"),
                ),
                (
                    "escalation_level",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Уровень эскалации"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_risk_incidents",
                        to="accounts.teacherprofile",
                        verbose_name="Ответственный преподаватель",
                    ),
                ),
                (
                    "escalated_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escalated_risk_incidents",
                        to="accounts.teacherprofile",
                        verbose_name="Эскалировано к",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_incidents",
                        to="app.group",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_incidents",
                        to="app.student",
                        verbose_name="Студент",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_incidents",
                        to="app.subject_study",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Риск-инцидент",
                "verbose_name_plural": "Риск-инциденты",
            },
        ),
        migrations.CreateModel(
            name="TeacherRiskIncidentAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("OPENED", "Инцидент создан"),
                            ("ACKNOWLEDGED", "Подтвержден"),
                            ("ESCALATED", "Эскалирован"),
                            ("RESOLVED", "Решен"),
                        ],
                        max_length=20,
                        verbose_name="Тип действия",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "payload",
                    models.JSONField(blank=True, null=True, verbose_name="Дополнительные данные"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата действия"),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="app.riskincident",
                        verbose_name="Инцидент",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_incident_actions",
                        to="accounts.teacherprofile",
                        verbose_name="Преподаватель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Действие по риск-инциденту",
                "verbose_name_plural": "Действия по риск-инцидентам",
            },
        ),
        migrations.AddIndex(
            model_name="riskincident",
            index=models.Index(
                fields=["student", "incident_type", "status"],
                name="app_riskinc_student_3624fc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="riskincident",
            index=models.Index(
                fields=["assigned_teacher", "status"],
                name="app_riskinc_assigne_f7dca7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="riskincident",
            index=models.Index(
                fields=["escalated_to", "status"], name="app_riskinc_escalat_6dd69a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riskincident",
            index=models.Index(
                fields=["group", "subject", "status"],
                name="app_riskinc_group_i_edd0f6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teacherriskincidentaction",
            index=models.Index(
                fields=["incident", "created_at"], name="app_teacher_inciden_86cbc1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teacherriskincidentaction",
            index=models.Index(
                fields=["teacher", "created_at"], name="app_teacher_teacher_a43c42_idx"
            ),
        ),
    ]
