# Generated by Django 5.2 on 2026-04-16 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0035_alter_notificationmodels_event_type_riskincident_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Оценка",
            ),
        ),
    ]
