# Generated by Django 5.2 on 2026-04-18 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('app', '0036_attendance_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Аудитория')),
                ('building', models.CharField(choices=[('main', 'Главный корпус'), ('other', 'Другой корпус')], default='main', max_length=16, verbose_name='Корпус')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoriums', to='accounts.teacherprofile', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
                'ordering': ['building', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='auditorium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='app.auditorium', verbose_name='Аудитория'),
        ),
        migrations.AddConstraint(
            model_name='auditorium',
            constraint=models.UniqueConstraint(fields=('teacher', 'building', 'name'), name='unique_auditorium_per_teacher_and_building'),
        ),
    ]
