# Generated by Django 5.2.13 on 2026-04-26 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_teacherprofile_telegram_chat_id"),
        ("app", "0037_auditorium_schedule_auditorium_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherNotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lesson_reminder_enabled",
                    models.BooleanField(default=True, verbose_name="Напоминание об уроке включено"),
                ),
                (
                    "reminder_minutes_before",
                    models.PositiveIntegerField(
                        default=30, verbose_name="За сколько минут до урока напоминать"
                    ),
                ),
                (
                    "teacher",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to="accounts.teacherprofile",
                        verbose_name="Преподаватель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки уведомлений преподавателя",
                "verbose_name_plural": "Настройки уведомлений преподавателей",
            },
        ),
        migrations.CreateModel(
            name="GroupLeadership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderships",
                        to="app.group",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leadership_roles",
                        to="app.student",
                        verbose_name="Студент-Староста",
                    ),
                ),
            ],
            options={
                "verbose_name": "Староста группы",
                "verbose_name_plural": "Старосты групп",
                "constraints": [
                    models.UniqueConstraint(fields=("group", "student"), name="unique_group_leader")
                ],
            },
        ),
    ]
