# Generated by Django 5.2 on 2026-04-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0038_teachernotificationsettings_groupleadership"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="presense",
        ),
        migrations.AddField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_marked", "Не отмечено"),
                    ("present", "Присутствовал"),
                    ("late", "Опоздал"),
                    ("absent", "Отсутствовал"),
                ],
                default="not_marked",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
