# Generated by Django 5.2 on 2026-05-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_teacherprofile_telegram_chat_id"),
        ("app", "0040_add_webhook_models"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(fields=["status", "schedule"], name="att_status_schedule_idx"),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(fields=["date"], name="schedule_date_idx"),
        ),
    ]
