# Generated by Django 5.2.13 on 2026-06-16 10:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0041_add_attendance_schedule_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceStatusSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("overall_status", models.CharField(max_length=20)),
                ("overall_severity", models.PositiveSmallIntegerField()),
                ("services", models.JSONField()),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="app_service_created_3ac39c_idx")
                ],
            },
        ),
    ]
